const quiz = [
    {
        q:'How do you write an if statement?',
        options: ['if ()','als ()', 'else ()', 'else if ()'],
        answer: 0,
        //img: 'img/square.png',
        topic: 'programming'
    },
    {
        q:'Which of these is an assignment operator?',
        options: ['=','==', '+', '/'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'Which for loop is correct?',
        options: ['for (1; x < 5; i--)','for(x; 5; ++1)', 'for(int i = 0; i < 5; i++)', 'for(int i = 0, i < 5, i++)'],
        answer: 2,
        topic:'programming',
    },
    {
        q:'Which while loop is correct?',
        options: ['while (true) { }','while true { }', 'continue (true) { }', 'while (1)'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'Which one will return an value?',
        options: ['give 1;','rerun 2;', '*a = 1;', 'return 1;'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'How do you invoke a function?',
        options: ['function { };','function[x];', 'function();', '(function);'],
        answer: 2,
        topic:'programming',
    },
    {
        q:'What will be the result? int a[2] = { 1, 5 }; int *p; p = a; p++;',
        options: ['*p = 1','p = 1', '*p = 5', 'p = 5'],
        answer: 2,
        topic:'programming',
    },
    {
        q:'What is a correct array?',
        options: ['int a() = { 1, 2 };','int a{} = [ 1, 2 ];', 'int a = ( 1, 2 );', 'int a[2] = { 1, 2 };'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'Which type is incorrect?',
        options: ['int','double', 'float', 'array'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'Which one is a function prototype?',
        options: ['void function ();','function ();', 'void function [];', '() function { };'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'Which function is correct?',
        options: ['void function () { }','function [] { }', 'function ( { } )', 'void function [ ] ( )'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'Which of these is NOT an arithmetic operator?',
        options: ['+','+=', '/', '>='],
        answer: 3,
        topic:'programming',
    },
    {
        q:'What is a named storage location that stores a value that can change known as?',
        options: ['Constant','Variable', 'Casting', 'Input'],
        answer: 1,
        topic:'programming',
    },
    {
        q:'What is a named storage location that stores a value that cannot change known as?',
        options: ['Constant','Variable', 'Print', 'Input'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'Data inside quotation marks is defined as which data type?',
        options: ['String','Integer', 'Float', 'Boolean'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'Which data type represents a whole number?',
        options: ['Float','Boolean', 'String', 'Integer'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'Which technique is used to convert what data type to another?',
        options: ['Convert','Transform', 'Change', 'Casting'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'Which of these is NOT a programming construct?',
        options: ['Sequence','Selection', 'Iteration', 'Subroutine'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'Which procedure is used to represent two outcomes in a selection statement?',
        options: ['IF-IF','IF-ELIF', 'IF-ELSE', 'IF * 2'],
        answer: 2,
        topic:'programming',
    },
    {
        q:'IF temperature > 40 is an example of what?',
        options: ['Loop','Condition', 'Outcome', 'All of the above'],
        answer: 1,
        topic:'programming',
    },
    {
        q:'The following figure is an example of simple flow chart. Flow chart is used in _____________ phase.',
        options: ['Analysis','Design', 'Coding', 'Testing'],
        answer: 1,
        img: 'img/flowchart.png',
        topic: 'programming'
    },
    {
        q:'Which of these is an example of an IDE?',
        options: ['Eclipse','Twilight', 'Moon', 'Saturn'],
        answer: 0,
        topic:'programming',
    },
    {
        q:'What does IDE stand for?',
        options: ['Integrated Debugging Equipment','Integrated Debugging Environment', 'Integrated Development Equipment', 'Integrated Development Environment'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'Process of finding and fixing errors in the syntax so the computer program will run properly',
        options: ['Bugs','Sequence', 'Debugging', 'Command'],
        answer: 2,
        topic:'programming',
    },
    {
        q:'What is Decomposition?',
        options: ['Breaking the problem down to look for specific patterns','Solving the problem by placing the algorithm into a single flowchart', 'Breaking the task down into smaller, more manageable tasks', 'Identifying where the algorithm needs to be repeated so that it save you time when writing it'],
        answer: 2,
        topic:'programming',
    },
    {
        q:'The spelling and grammar of a programming language is',
        options: ['diction','syntax', 'vocabulary', 'semantics'],
        answer: 1,
        topic:'programming',
    },
    {
        q:'What is the following code doing: TotalMarks = 8',
        options: ['Declaring a variable','Assigning a value to a variable', 'Performing a calculation', 'Finding the running total'],
        answer: 1,
        topic:'programming',
    },
    {
        q:'Which statement is true about Java?',
        options: ['Java is a sequence-depended programming language','Java is a code dependent programming language', 'Java is a platform-dependent programming language', 'Java is a platform-independent programming language'],
        answer: 3,
        topic:'programming',
    },
    {
        q:'If Jenny is 13, which message will be printed?',
        options: ['Message 1','Message 2', 'Message 3', 'Message 4'],
        answer: 0,
        img: 'img/message.png',
        topic:'programming',
    },
]
